### PR TITLE
Add re-setcred feature

### PR DESCRIPTION
**Pull request by Lertsenem**
Hello !

Thank youy for your rewrite of xtrlock in python with libpam support ! I like xtrlock but it was improper to use with network-based (or just modern) authentication solutions.
I found your port lacked the ability to reset my credentials at login though, so I don't have to retype 'kinit' every once in a while to get a new Kerberos ticket (yeah, I'm lazy). So here is the patch to do just that. :]

Regards.

### CODE REVIEW

**Comment by leonnnn** [comment]
Thanks for the input! I'm hoping to find the time to review the patch in a couple of days (will have to read some pam docs etc).

**Comment by Lertsenem** [comment]
Just to let you know: I did not read the entire pam doc.

I knew that xscreensaver provided the functionality, so I just took a look at their sources to see how they did it.

**Comment by leonnnn** [comment]
Because you override `retval` with the return value of `pam_setcred()` and `retval == 0`, the code will return an authentication failure in case `pam_setcred()` returns a nonzero value (which is non-fatal), even though `pam_authentication()` has returned 0 (`PAM_SUCCESS`).

I have prepared an amended patch in [branch resetcred](https://github.com/leonnnn/python3-simplepam/tree/resetcred). Can you test and review?

**Comment by Lertsenem** [comment]
This looks good to me (and worked well on my machine).

**Pull request closed without merging**
